spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://east-wind.mysql.zhangbei.rds.aliyuncs.com:3306/blog?useSSL=false&tinyInt1isBit=false
        username: east_wind
        password: eastWind123456
    thymeleaf:
        prefix: classpath:/templates/
        check-template-location: true
        suffix: .html
        mode: HTML
        cache: false
    devtools:
        restart:
            # classpath目录下的WEB-INF文件夹内容修改不重启
            exclude: WEB-INF/**
            # 设置重启的目录
            additional-paths: src/main/java
            # 热部署生效
            enabled: true
    # 文件上传
    application:
        name: ware-fast-dfs
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB
    redis:
        # 主机ip
        host: 39.97.214.10
        # Redis服务器连接端口
        port: 6379
        jedis:
            pool:
                # 连接池最大连接数（使用负值表示没有限制）
                max-active: 100
                # 连接池中的最小空闲连接
                max-idle: 10
                # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: 100000
        # 连接超时时间（毫秒）
        timeout: 5000
        # 默认是索引为0的数据库
        database: 0
    # activemq配置
    activemq:
        broker-url: tcp://39.97.214.10:61616
        user: admin
        password: admin
        # 默认代理URL是否应该在内存中。如果指定了显式代理，则忽略此值。
        in-memory: true
        # 等待消息发送响应的时间。设置为0等待永远。
        send-timeout: 0
        # 是否在回滚回滚消息之前停止消息传递。这意味着当启用此命令时，消息顺序不会被保留。
        non-blocking-redelivery: false
        # 是否用PooledConnectionfactory代替普通的ConnectionFactory
        pool:
            enabled: false
        packages:
            trust-all: true   # 如果使用ObjectMessage传输对象，必须要加上这个信任包，否则会报ClassNotFound异常
    jms:
        #默认情况下activemq提供的是queue模式，若要使用topic模式需要配置下面配置
        pub-sub-domain: true
    data:
        mongodb:
            uri: mongodb://39.97.214.10:27017/test
server:
    port: 9090
    servlet:
        context-path: /blog
logging:
    level:
        root: info
        com.monster.blog: debug
    file:
        name: logs/spring.log
        max-history: 1
        max-size: 10MB
mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        callSettersOnNulls: true
        map-underscore-to-camel-case: true
    mapper-locations: classpath:/mapper/*Mapper.xml

pagehelper:
    helper-dialect: mysql
    params: count=countSql
    reasonable: true
    support-methods-arguments: true

# 上传图片服务器配置
nginx.username: root
nginx.password: Xyc86418332
nginx.ip: 39.97.214.10
nginx.port: 80
nginx.id: 22
nginx.uploadPath: /usr/local/nginx/html

# FastDFS文件管理服务器
fdfs:
    # 链接超时
    connect-timeout: 6000
    # 读取时间
    so-timeout: 6000
    # 生成缩略图参数
    thumb-image:
        width: 150
        height: 150
    tracker-list: 39.97.214.10:22122



